# Copyright (C) 2026, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

"""Knowing the host key of a machine before ever connecting to it.

A first SSH connection to a machine whose key is unknown either prompts, which
hangs a run forever, or is waved through with `StrictHostKeyChecking=no`, which
is a real man in the middle window on the administration network. Neither is
acceptable on a substation.

For the local machine there is a third answer, and it is strictly better than
both: read the host's own public host keys off its filesystem. No network is
involved, so there is nothing to intercept. The quadlet mounts `/etc/ssh` read
only for exactly this.

The same shape works for a peer at M3, where the host key travels over the
mutually authenticated TLS channel rather than over the wire unverified.
"""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

# Modern algorithms only. An RSA host key still works, but offering it here
# would let a downgrade decide which key gets compared.
_HOST_KEY_FILES = ("ssh_host_ed25519_key.pub", "ssh_host_ecdsa_key.pub")

_HEADER = (
    "# Generated by seapath-webui from the host's own public host keys.\n"
    "# Read from the filesystem, never from the network.\n"
)


def read_local_host_keys(ssh_config_dir: Path) -> list[str]:
    """The machine's public host keys, as `<type> <blob>` without a comment."""
    keys: list[str] = []
    for name in _HOST_KEY_FILES:
        try:
            content = (ssh_config_dir / name).read_text().strip()
        except OSError:
            continue
        fields = content.split()
        if len(fields) >= 2:
            keys.append(f"{fields[0]} {fields[1]}")
    return keys


def render(entries: dict[str, list[str]]) -> str:
    """`known_hosts` content: one line per name and per key, sorted."""
    lines = []
    for name in sorted(entries):
        for key in sorted(entries[name]):
            lines.append(f"{name} {key}")
    return _HEADER + "".join(f"{line}\n" for line in lines)


def ensure_local(
    known_hosts_file: Path,
    ssh_config_dir: Path,
    names: list[str],
) -> bool:
    """Record this machine's host keys under every name it answers to.

    Returns whether the file changed. Rewritten wholesale rather than merged:
    unlike `authorized_keys`, this file belongs to the service alone, so there
    is nothing of anyone else's in it to preserve.
    """
    keys = read_local_host_keys(ssh_config_dir)
    if not keys:
        logger.warning(
            "No SSH host key found under %s, so runs against this machine "
            "would have to accept an unverified key. Check that the quadlet "
            "mounts /etc/ssh.",
            ssh_config_dir,
        )
        return False

    content = render({name: keys for name in names if name})
    known_hosts_file.parent.mkdir(parents=True, exist_ok=True)
    if known_hosts_file.exists() and known_hosts_file.read_text() == content:
        return False
    known_hosts_file.write_text(content)
    logger.info(
        "Recorded %d host key(s) for %s in %s",
        len(keys),
        ", ".join(names),
        known_hosts_file,
    )
    return True
